name: "Xml SiteMap Generator"
description: "Generates an XML SiteMap for your website."
author: "FullStackIndie"
branding:
  icon: "zap"
  color: "gray-dark"
inputs:
  url:
    description: "Your website domain to crawl. Must start with http:// or https://"
    required: true
  cache-key:
    description: "The cache key to upload artifact. You will use the same key to download the artifact. Default: sitemap"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: "7.0.x"

    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        repository: "FullStackIndie/sitemap-generator"

    - name: Build SiteMap Generator
      shell: bash
      run: |
        # mkdir ./sitemap-generator
        # cd ./sitemap-generator
        # git clone https://github.com/FullStackIndie/sitemap-generator.git .
        dotnet publish ./SiteMapGenerator.csproj -c Release -r linux-x64 --self-contained true -o ./build
        chmod +x ./build/SiteMapGenerator

    - name: Run SiteMap Generator
      shell: bash
      run: |
        cd ${{ github.workspace }}
        ./build/SiteMapGenerator ${{ inputs.url }} -P="." -L="."

    - name: Upload SiteMap Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.cache-key }}
        path: |
          ./build/sitemap.xml
          ./build/sitemap_generator_logs.txt
        retention-days: 1
